"""Updated User model, added confirmation_code

Revision ID: 090427f256df
Revises: 64a6b6c07019
Create Date: 2024-08-06 16:57:33.186579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "090427f256df"
down_revision: Union[str, None] = "64a6b6c07019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("confirmation_code", sa.String(length=4), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmation_code")
    # ### end Alembic commands ###
