"""Updated User model, address -> location

Revision ID: 64a6b6c07019
Revises: c0b3e79f1cd3
Create Date: 2024-08-01 20:58:22.977122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '64a6b6c07019'
down_revision: Union[str, None] = 'c0b3e79f1cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.String(length=120), nullable=True))
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
