"""Updated User model, added communication channels, location field has been made mandatory, removed confirmation code

Revision ID: ccdb06b71369
Revises: 090427f256df
Create Date: 2024-08-13 19:43:50.651090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccdb06b71369'
down_revision: Union[str, None] = '090427f256df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prefers_phone_call', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('prefers_telegram', sa.Boolean(), nullable=False))
    op.alter_column('users', 'location',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('users', 'confirmation_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmation_code', mysql.VARCHAR(length=4), nullable=True))
    op.alter_column('users', 'location',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_column('users', 'prefers_telegram')
    op.drop_column('users', 'prefers_phone_call')
    # ### end Alembic commands ###
